apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Add your environment variables here.
  # This file should not be committed to version control with real secrets.
  DATABASE_URL: "postgresql://user:password@endpoint:5432/db"
  
  # Firebase environment variables
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyC6tZpGCr2hd9oJIBmHfboLKH0OdM2j7UA"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "cloud-cognizance.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "cloud-cognizance"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "cloud-cognizance.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "500971545313"
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:500971545313:web:b2d76c2cca19541a7ccda0"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "G-9Y28E45ND5"

  # Firebase Admin variables
  FIREBASE_PROJECT_ID: "cloud-cognizance"
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-fbsvc@cloud-cognizance.iam.gserviceaccount.com"
  FIREBASE_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDH7jE8njHcrPA0
    YO4EylzUocyDtTdgO+GRmTZxssY/n9Jg67f8NWZ6L8Vr0rFSZxv0+oxDHP0XG87H
    G/4D2uueR0irn//5Tg+7ZeX2qjE09o31hL7i67UxPyNiWq1TvvqamWO7Sd+55Css
    IdYfsLkNVNo2x/Q4QzU5TYAtG7EWmzbjJp1adX2UYqEssW+XZjZlY/wUYWPfuVpc
    apBTYKjm/ZOGZ1Jks9WJ9yA0hSKwpvgtaMVwt+4VHNrL8SFPEpXojddhLk5mcVUW
    eQ9Q58AIFyYbm6vff/x0CeClcXu5cexFqooN8VtWRGRee+oszECPU5hhStT32ZdR
    XkestlQJAgMBAAECggEABYp4HXZDt7Pbrl/w7y7akF8+YN7g8ei6JJDEXc9Qewsg
    +sp3Nv6veeIHP/WlY3BaUBl96w6lHWkjlTuuq29ISc+VvhsflLDrDH/TXHKbQLZq
    kpJ2WQ/WRDVvQIN2ohQ9AGB3tdH8zztf6CFOvJWA820ifq0sLnKYyYWr1tQzJFPm
    Khz5/PPSkWQSm4GNY4IHCsmuGG/TePc7L3anR4yU+0ckAHT528h1gr/mIHMDrZTz
    /ukLuHkk2Es2EHP0H+WaJtYYoPCCxXMWlpAqRpWjcn8Rw8siLV+C9PfjV1BQl3rz
    qk3ll+rZrYD44gRmyMx5CnpdbnOmqTCLeTcrXym2uQKBgQDmJgYxbP2xqK3HPvyW
    J+w+1Sm1/3Vr+mzTryE27Voi7fUaOp02V8Pej0ZhB5D5eYXXGRtBjhU5K3RNfExM
    5jJA/D+33nBFjMRTJ/JQ+UBOHTdiVVNT5eCuCFYKoYBeHl0nY5rEj/ETkbt1QE/3
    N438ZxJYxSSQhN1xbElgk8r/nQKBgQDeYz1bi62e9QRqW9jj1Cp3bWWTHtAojSae
    V6unJNfsG5qfmwETh3HujKqs41wwdeNiTNSQrjVtxaOKTMe3jQoLfB6de6zk31Vc
    sZLm1EMoUyEgdz2Jh93PxQN4Frx1Hql9Hp4HSKIAmLUxZGEHb/iI468SegsFUFNX
    o+b4YwfYXQKBgQCyKveaZcTUN0AowiMqX0etsLm0skoFyH1dNvOgoQiph8u6fWvd
    eP4iGoqibQgXibNKPJ50Fnlpo7FKlxI+aeq3klAFmMcToJEPyxn1A7B7iHSqxGFY
    ztosADoTyskkk58L8jkLOF+qBaS4dYwyVyitIGH8pMnUs3b26py3jlKVpQKBgQDe
    TKdd5l8UoWnbg5poC4KzxQgfK1L65jXvXEW7G8o3O1SyLLjDs8YApl5J2jAiRQWa
    EqD9SxcfdsvGiH+vjG25E0ZrN+CZHGJw+RSWZyIGoipgELHT05u3gAG6vkd+b7sO
    1lczgrhmDkA5clTHoXb4J1ivCI4RrrzQw4czTZLfBQKBgQCkMWY03T/qDVxk28nv
    xBEQq/BnUB/3lLCNOfLnpaHdWgvhbgsay7xio8mn384cGTIdXboYtZLt3fQ9IOcN
    uHNjAcde96N/VIZbHePOX99de0SU5y4l6RkP6puvYQKOsGr5i6/AhwU1IhZdRuE8
    3oHbgITpoyTSZbGGgekbSb2H2A==
    -----END PRIVATE KEY-----
